apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo
        image: stark985/todoapp:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
