name: Deploy to Minikube

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check deployment
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
