name: Deploy to Minikube

on:
  #push:
  #  branches:
  #    - main  # Trigger deployment on push to the 'main' branch
  workflow_run:
    workflows: ["CI Pipeline"]  # Name of the CI workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check deployment
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
