name: CI Pipeline

on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install fastapi
          pip install pydantic
          pip install pytest
          pip install uvicorn

      # Lint the code (using pylint for Python)
      - name: Lint with Pylint
        run: |
          pylint main.py  # or your file path

      # Run tests using pytest (or unittest)
      - name: Run tests
        run: |
          pytest tests/--maxfail=1 --disable-warnings -q  # Fail fast on the first error
